// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: api/cel-service.proto

package protofiles

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ContextValue_Type int32

const (
	ContextValue_int23  ContextValue_Type = 0
	ContextValue_int64  ContextValue_Type = 1
	ContextValue_double ContextValue_Type = 2
	ContextValue_float  ContextValue_Type = 3
	ContextValue_bool   ContextValue_Type = 4
	ContextValue_string ContextValue_Type = 5
	ContextValue_bytes  ContextValue_Type = 6
)

// Enum value maps for ContextValue_Type.
var (
	ContextValue_Type_name = map[int32]string{
		0: "int23",
		1: "int64",
		2: "double",
		3: "float",
		4: "bool",
		5: "string",
		6: "bytes",
	}
	ContextValue_Type_value = map[string]int32{
		"int23":  0,
		"int64":  1,
		"double": 2,
		"float":  3,
		"bool":   4,
		"string": 5,
		"bytes":  6,
	}
)

func (x ContextValue_Type) Enum() *ContextValue_Type {
	p := new(ContextValue_Type)
	*p = x
	return p
}

func (x ContextValue_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContextValue_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_cel_service_proto_enumTypes[0].Descriptor()
}

func (ContextValue_Type) Type() protoreflect.EnumType {
	return &file_api_cel_service_proto_enumTypes[0]
}

func (x ContextValue_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContextValue_Type.Descriptor instead.
func (ContextValue_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_cel_service_proto_rawDescGZIP(), []int{1, 0}
}

type CelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context    map[string]*ContextValue `protobuf:"bytes,1,rep,name=Context,proto3" json:"Context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Expression string                   `protobuf:"bytes,2,opt,name=Expression,proto3" json:"Expression,omitempty"`
}

func (x *CelRequest) Reset() {
	*x = CelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cel_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelRequest) ProtoMessage() {}

func (x *CelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cel_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelRequest.ProtoReflect.Descriptor instead.
func (*CelRequest) Descriptor() ([]byte, []int) {
	return file_api_cel_service_proto_rawDescGZIP(), []int{0}
}

func (x *CelRequest) GetContext() map[string]*ContextValue {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CelRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type ContextValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  ContextValue_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protofiles.ContextValue_Type" json:"type,omitempty"`
	Value []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ContextValue) Reset() {
	*x = ContextValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cel_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextValue) ProtoMessage() {}

func (x *ContextValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_cel_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextValue.ProtoReflect.Descriptor instead.
func (*ContextValue) Descriptor() ([]byte, []int) {
	return file_api_cel_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContextValue) GetType() ContextValue_Type {
	if x != nil {
		return x.Type
	}
	return ContextValue_int23
}

func (x *ContextValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CelResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Result  bool   `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *CelResult) Reset() {
	*x = CelResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_cel_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelResult) ProtoMessage() {}

func (x *CelResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_cel_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelResult.ProtoReflect.Descriptor instead.
func (*CelResult) Descriptor() ([]byte, []int) {
	return file_api_cel_service_proto_rawDescGZIP(), []int{2}
}

func (x *CelResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CelResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CelResult) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_api_cel_service_proto protoreflect.FileDescriptor

var file_api_cel_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x65, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x0a, 0x43, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x43, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x1a, 0x54, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xad, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x54, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x69, 0x6e, 0x74,
	0x32, 0x33, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x10, 0x06, 0x22, 0x53, 0x0a, 0x09, 0x43, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x12, 0x5a, 0x10,
	0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_cel_service_proto_rawDescOnce sync.Once
	file_api_cel_service_proto_rawDescData = file_api_cel_service_proto_rawDesc
)

func file_api_cel_service_proto_rawDescGZIP() []byte {
	file_api_cel_service_proto_rawDescOnce.Do(func() {
		file_api_cel_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_cel_service_proto_rawDescData)
	})
	return file_api_cel_service_proto_rawDescData
}

var file_api_cel_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_cel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_cel_service_proto_goTypes = []interface{}{
	(ContextValue_Type)(0), // 0: protofiles.ContextValue.Type
	(*CelRequest)(nil),     // 1: protofiles.CelRequest
	(*ContextValue)(nil),   // 2: protofiles.ContextValue
	(*CelResult)(nil),      // 3: protofiles.CelResult
	nil,                    // 4: protofiles.CelRequest.ContextEntry
}
var file_api_cel_service_proto_depIdxs = []int32{
	4, // 0: protofiles.CelRequest.Context:type_name -> protofiles.CelRequest.ContextEntry
	0, // 1: protofiles.ContextValue.type:type_name -> protofiles.ContextValue.Type
	2, // 2: protofiles.CelRequest.ContextEntry.value:type_name -> protofiles.ContextValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_cel_service_proto_init() }
func file_api_cel_service_proto_init() {
	if File_api_cel_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_cel_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cel_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_cel_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CelResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_cel_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_cel_service_proto_goTypes,
		DependencyIndexes: file_api_cel_service_proto_depIdxs,
		EnumInfos:         file_api_cel_service_proto_enumTypes,
		MessageInfos:      file_api_cel_service_proto_msgTypes,
	}.Build()
	File_api_cel_service_proto = out.File
	file_api_cel_service_proto_rawDesc = nil
	file_api_cel_service_proto_goTypes = nil
	file_api_cel_service_proto_depIdxs = nil
}
